### PR TITLE
Redirect to apidoc canonical path on page not found exception

### LINKED ISSUE #20: SmartDocs "Page not Found" when refreshing or using back button
When viewing an API Doc entity using the SmartDocs formatter for the API specification, you cannot use the back button to go back to the previous page.

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #20 
This is a fix that implements an event subscriber to redirect back to an apidoc canonical page on page not found exception. It checks for `/api/ID/foo/bar` uri and validates `/api/ID` paths and redirect to that.

This can be a temp fix for the page not found issue on apidocs. 

Instead of seeing a page not found on refresh, the user sees the overview for the smartdocs.

### CODE REVIEW

File: src/EventSubscriber/PageNotFoundEventSubscriber.php [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+   *
+   * @param \Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent $event
+   *   The exception event.
+   */
+  public function onNotFoundException(GetResponseForExceptionEvent $event) {
+    $path = NULL;
+
+    // Check if the request uri matches an apidoc canonical route.
+    // Also check for apidoc valid path.
+    if (!($event->getException() instanceof NotFoundHttpException)
```
Comment (Jaesin) [inline src/EventSubscriber/PageNotFoundEventSubscriber.php]: Would this not always be true?

**Review by Jaesin — APPROVED** [review]
This is a intermediate solution in my opinion.

Of course we can add routes for smartdoc paths but there would be several and we should be fairly confident they won't change.

Adding routes would look something like: 

```
entity.apidoc.catchall:
  path: /api/{apidoc}/{smartdocs_1}/{smartdocs_2}
  defaults:
    _entity_view: apidoc.full
    _title_callback: \Drupal\Core\Entity\Controller\EntityController::title
  requirements:
    _entity_access: apidoc.view
    apidoc: '\d+'
  options:
    parameters:
      apidoc:
        - type: 'entity:apidoc'
        - converter: 'paramconverter.entity'

entity.apidoc.catchall_2:
  path: /api/{apidoc}/{smartdocs_1}/{smartdocs_2}/{smartdocs_3}
  defaults:
    _entity_view: apidoc.full
    _title_callback: \Drupal\Core\Entity\Controller\EntityController::title
  requirements:
    _entity_access: apidoc.view
    apidoc: '\d+'
  options:
    parameters:
      apidoc:
        - type: 'entity:apidoc'
        - converter: 'paramconverter.entity'

entity.apidoc.catchall_3:
  path: /api/{apidoc}/{smartdocs_1}/{smartdocs_2}/{routes}/{smartdocs_4}
  defaults:
    _entity_view: apidoc.full
    _title_callback: \Drupal\Core\Entity\Controller\EntityController::title
  requirements:
    _entity_access: apidoc.view
    apidoc: '\d+'
  options:
    parameters:
      apidoc:
        - type: 'entity:apidoc'
        - converter: 'paramconverter.entity'

```

Of course there are a couple of other routing solutions that we can evaluate them but this is working now.

File: src/EventSubscriber/PageNotFoundEventSubscriber.php [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+      || !(($uri = $event->getRequest()->getRequestUri())
+        && ($this->pathMatcher->matchPath($uri, '/api/*/*'))
+        && ([, $prefix, $id] = explode('/', $uri))
```
Comment (cnovak) [inline src/EventSubscriber/PageNotFoundEventSubscriber.php]: The $prefix is never used

File: src/EventSubscriber/PageNotFoundEventSubscriber.php [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+   * @param \Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent $event
+   *   The exception event.
+   */
+  public function onNotFoundException(GetResponseForExceptionEvent $event) {
+    $path = NULL;
+
+    // Check if the request uri matches an apidoc canonical route.
+    // Also check for apidoc valid path.
+    if (!($event->getException() instanceof NotFoundHttpException)
+      || !(($uri = $event->getRequest()->getRequestUri())
```
Comment (cnovak) [inline src/EventSubscriber/PageNotFoundEventSubscriber.php]: This logic is a bit difficult to understand when looking at it, would be good to rewrite in a way that is less concise but easier to read.

File: src/EventSubscriber/PageNotFoundEventSubscriber.php (hunk 2 above)
Comment (shadcn) [reply src/EventSubscriber/PageNotFoundEventSubscriber.php]: Fixed.

File: src/EventSubscriber/PageNotFoundEventSubscriber.php (hunk 3 above)
Comment (shadcn) [reply src/EventSubscriber/PageNotFoundEventSubscriber.php]: Fixed.

**Comment by cnovak** [comment]
Tests pass:
```
../vendor/bin/phpunit --configuration core modules/contrib/apigee_api_catalog/ 
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Testing modules/contrib/apigee_api_catalog/
...............                                                   15 / 15 (100%)

Time: 3.32 minutes, Memory: 8.00MB

OK (15 tests, 169 assertions)

```
