### PR TITLE
[#109] Add back deprecated apidoc table to avoid update issues

### LINKED ISSUE #109: Issues with previous version of API Catalog cause issues when trying to upgrade to the Fix.
Issues created with the previous version of the API Catalog that were corrected in the following build, Apigee API catalog 8.x-2.4 , are unable to be resolved and are preventing me from updating to that build due to the errors below. I am unable to uninstall or upgrade any module as this error is always thrown. I am hoping to get the new version of Apigee API Catalog to resolve all of the issues we've had with it.

[01-Oct-2020 17:43:49 UTC] Uncaught PHP Exception
Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException: "The
"apidoc" entity type did not specify a access handler." at
/code/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 272
[01-Oct-2020 17:46:11 UTC] Uncaught PHP Exception
Drupal\Core\Database\DatabaseExceptionWrapper: "SQLSTATE[42S02]: Base table
or view not found: 1146 Table 'pantheon.apidoc' doesn't exist: SELECT
base_table.revision_id AS revision_id, base_table.id AS id
FROM
{apidoc} base_table
GROUP BY base_table.revision_id, base_table.id
LIMIT 1 OFFSET 0; Array
(
)
" at /code/web/core/lib/Drupal/Core/Database/Connection.php line 701
[01-Oct-2020 17:49:42 UTC] Uncaught PHP Exception
Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException: "The
"apidoc" entity type did not specify a access handler." at
/code/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 272

### PR DESCRIPTION
**Pull request by arlina-espinoza**
Fixes #109 . Disables previous update step that uninstalls the apidoc entity and table, and adds a new update function that re-installs it (for users that already have this problem).

### CODE REVIEW

File: src/UpdateService.php [hunk 1]
```diff
@@ -316,6 +316,22 @@ public function update8805() {
...
 
+  /**
+   * Recreate API Doc entity definition.
+   *
+   * Rollback update8805().
+   */
+  public function update8806() {
+    \Drupal::entityTypeManager()->clearCachedDefinitions();
+    $entity_definition_update_manager = \Drupal::entityDefinitionUpdateManager();
+    $entity_definition_update_manager->installEntityType(\Drupal::entityTypeManager()->getDefinition('apidoc'));
```
Comment (giteshk) [inline src/UpdateService.php:327]: Do we need to check if the EntityType is installed (table exists)?  If someone is migrating from version 8805 to 8806 ?

Comment (arlina-espinoza) [reply src/UpdateService.php:327]: Just tested this scenario from 8805 with an existing table to 8806, and it does not throw nor log an error, so it should be good.

**Review by shadcn — APPROVED** [review]
Tested. Looks good. 

The storage schema checks for existing tables.

```php
if (!$schema_handler->tableExists($table_name)) {
    $schema_handler->createTable($table_name, $table_schema);
}
```
