### PR TITLE
Fix deprecated method and class getException() and GetResponseForExceptionEvent

### LINKED ISSUE #183: Call to deprecated method getException() & class Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent
## Description
- Deprecated class `Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent`: since Symfony 4.3 and 
- Deprecated method `getException()` of class `Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent: `since Symfony 4.4.
See https://www.drupal.org/project/drupal/issues/3113876

## Version Info
Drupal 9, Symfony 4.3/4.4

### PR DESCRIPTION
**Pull request by shishir-intelli**
Closes #183

Fixes deprecated class `Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent` and deprecated method `getException()` for same class.

See https://www.drupal.org/project/drupal/issues/3113876

### CODE REVIEW

File: src/EventSubscriber/PageNotFoundEventSubscriber.php [hunk 1]
```diff
@@ -24,7 +24,7 @@
 use Drupal\Core\Path\PathValidatorInterface;
 use Symfony\Component\EventDispatcher\EventSubscriberInterface;
 use Symfony\Component\HttpFoundation\RedirectResponse;
-use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;
+use Symfony\Component\HttpKernel\Event\ExceptionEvent;
```
Comment (phdhiren) [inline src/EventSubscriber/PageNotFoundEventSubscriber.php:27]: @shishir-intelli Do you believe that we need to update the module's Drupal version to 9, to accept this change?

Comment (shishir-intelli) [reply src/EventSubscriber/PageNotFoundEventSubscriber.php:27]: @phdhiren 
Yes, This method has been deprecated since Symfony 4.4

**Review by phdhiren — APPROVED** [review]
LGTM
